server:
  port: 9000
spring:
  application:
    name: auth-service
  config:
    activate:
      on-profile: local, dev, local
    import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"