spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: 5dca3ee52a5c5e81b0415473b05366f0
            client-secret: RifFZkO0SBAISOUJn2XsGVRczr0h9qFj
            client-authentication-method: client_secret_post
            redirect-uri: ${oauth.redirect.domain}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email


  mail:
    host: ${email.send.host}
    port: 587
    username: ${email.send.email}
    password: ${email.send.passord}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000





email:
  send:
    from: ${email.send.from}


jwt:
  access:
    secret: ${jwt.access.secret}
    lifetime: ${jwt.access.lifetime}
  refresh:
    secret: ${jwt.refresh.secret}
    lifetime: ${jwt.refresh.lifetime}



redis:
  hostname: ${redis.hostname}
  port: ${redis.port}


cookie:
  refresh:
    token:
      name: ${cookie.refresh.token.name}


system:
  admin:
    id: ${system.admin.id}
    password: ${system.admin.password}