server:
  port: 8081
spring:
  redis:
    host: localhost
    port: 6379
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/bb-auth-service?serverTimezone=Asia/Seoul
    username: root
    password: k1651227
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: 5dca3ee52a5c5e81b0415473b05366f0
            client-secret: RifFZkO0SBAISOUJn2XsGVRczr0h9qFj
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email


  mail:
    host: smtp.gmail.com
    port: 587
    username: rnwldnd7249@gmail.com
    password: hani bvmt tiao yxdv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

redis:
  hostname: localhost
  port: 6379


email:
  send:
    from: bbFlower@no-reply.co.kr




cookie:
  refresh:
    http:
      domain: localhost:8081
    token:
        name: refresh-cookie

system:
  admin:
    id: bb-flower
    password: bb-flower-password

store:
  manager:
    id: store-manageer-id
    password: store-manager-password

security:
  authorization:
    header:
      name: Authorization

kakao:
  login:
    request:
      uri: "/api/auth/social/kakao/login"
