server:
  port: 9000
spring:
  application:
    name: auth-service
  config:
    activate:
      on-profile: prod
    import: optional:configserver:http://config-service:8888
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"
