server:
  port: 9000
spring:
  application:
    name: auth-service
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://localhost:8888


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: 7f313aaa30b302cd7ae2b48cf2d2b7cd
            client-secret: Wl5VDUbX9KsRymQW2S4MhoPvAPqdD7kC
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:3000
            authorization-grant-type: authorization_code
            admin-key: ffc238f9c4e55c2fa85f551f882eda68
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
              - phone_number


  mail:
    host: smtp.gmail.com
    port: 587
    username: rnwldnd7248@gmail.com
    password: ${mail.host.port.password}
    properties:
      mail:
       smtp:
        auth: true
        starttls:
          enable: true


email:
  send:
    from: bbFlower@no-reply.co.kr



cookie:
  refresh:
    http:
      domain: localhost:9000
    token:
      name: refresh-cookie

system:
  admin:
    id: 100
    password: bb-flower-password


kakao:
  logout:
    redirect: http://localhost:3000


service:
  user:
    domain: http://localhost:8600


management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"


user:
  info:
    secret: user-secret-user-secret-user-secret-user-secret-user-secret


