server:
  port: 9000
  servlet:
    session:
      cookie:
        same-site: none

spring:
  application:
    name: auth-service

  redis:
    host: redis
    port: 6379
    password: 123456

  config:
    activate:
      on-profile: local
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/develop?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: 7f313aaa30b302cd7ae2b48cf2d2b7cd
            client-secret: Wl5VDUbX9KsRymQW2S4MhoPvAPqdD7kC
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:3000/login/oauth
            authorization-grant-type: authorization_code
            admin-key: ffc238f9c4e55c2fa85f551f882eda68
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
              - phone_number


  mail:
    host: smtp.gmail.com
    port: 587
    username: rnwldnd7248@gmail.com
    password: ${mail.host.port.password}
    properties:
      mail:
       smtp:
        auth: true
        starttls:
          enable: true


email:
  send:
    from: bbFlower@no-reply.co.kr



cookie:
  refresh:
    http:
      domain: localhost:9000
    token:
      name: refresh-cookie

system:
  admin:
    id: 100
    password: bb-flower-password


kakao:
  logout:
    redirect: http://localhost:3000


service:
  user:
    domain: http://localhost:8600
  store:
    domain: http://localhost:5000


management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"


user:
  info:
    secret: user-secret-user-secret-user-secret-user-secret-user-secret


encrypt:
  key:
    access: access-keyaccess-keyaccess-keyaccess-keyaccess-keyaccess-keyaccess-key
    refresh: refresh-keyrefresh-keyrefresh-keyrefresh-keyrefresh-keyrefresh-keyfresh-key