name: PR build


on:
  pull_request:
    branches: [ dev ] # develop branch에 PR을 보낼 때 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DEV_DOCKER_ID }}
          password: ${{ secrets.DEV_DOCKER_PW }}
      - name: redis run 
        run: docker run -p 6379:6379 -d reids redis-server --appendonly yes --requirepass "12345"

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Gradle wrapper 파일 실행 권한주기
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle test를 실행한다
      - name: build gradle
        run: ./gradlew clean build
